### ISSUE TITLE
How would I configure httpBearer instead of oauth2?

### ISSUE THREAD

**Issue by qrkourier** [BerkleyTechnologyServices/restdocs-spec#71]
I'd like to use a simplified auth type where the user has a JWT bearer token on their clipboard and pastes it into the playground derived from the generated spec file.

How would I configure the plugin to generate this? In .components.securitySchemes
```yaml
httpBearer:
    type: http
    scheme: bearer
```
and in .security
```yaml
security:
    - httpBearer:
```

Thank you for any guidance!
